/**
 * Vanilla Bedrock enchantment-name lang entries, copied from Mojang/bedrock-samples (main branch,
 * resource_pack/texts/en_US.lang and ru_RU.lang, fetched 2026-09-24). Test fixture only: the game ships these
 * itself; the add-on only references the keys.
 */
export const VANILLA_ENCHANT_LANG: Readonly<Record<string, { en: string; ru: string }>> = {
  "enchantment.arrowDamage": { en: "Power", ru: "Мощь" },
  "enchantment.arrowFire": { en: "Flame", ru: "Воспламенение" },
  "enchantment.arrowInfinite": { en: "Infinity", ru: "Бесконечность" },
  "enchantment.arrowKnockback": { en: "Punch", ru: "Удар" },
  "enchantment.crossbowMultishot": { en: "Multishot", ru: "Залп" },
  "enchantment.crossbowPiercing": { en: "Piercing", ru: "Бронебойность" },
  "enchantment.crossbowQuickCharge": { en: "Quick Charge", ru: "Быстрая перезарядка" },
  "enchantment.curse.binding": { en: "Curse of Binding", ru: "Проклятие связи" },
  "enchantment.curse.vanishing": { en: "Curse of Vanishing", ru: "Проклятие утраты" },
  "enchantment.damage.all": { en: "Sharpness", ru: "Острота" },
  "enchantment.damage.arthropods": { en: "Bane of Arthropods", ru: "Бич членистоногих" },
  "enchantment.damage.undead": { en: "Smite", ru: "Небесная кара" },
  "enchantment.digging": { en: "Efficiency", ru: "Эффективность" },
  "enchantment.durability": { en: "Unbreaking", ru: "Неразрушимость" },
  "enchantment.fire": { en: "Fire Aspect", ru: "Облик огня" },
  "enchantment.fishingSpeed": { en: "Lure", ru: "Приманка" },
  "enchantment.frostwalker": { en: "Frost Walker", ru: "Морозная поступь" },
  "enchantment.heavy_weapon.breach": { en: "Breach", ru: "Пробитие" },
  "enchantment.heavy_weapon.density": { en: "Density", ru: "Плотность" },
  "enchantment.heavy_weapon.windburst": { en: "Wind Burst", ru: "Порыв ветра" },
  "enchantment.knockback": { en: "Knockback", ru: "Отбрасывание" },
  "enchantment.lootBonus": { en: "Looting", ru: "Добыча" },
  "enchantment.lootBonusDigger": { en: "Fortune", ru: "Удача" },
  "enchantment.lootBonusFishing": { en: "Luck of the Sea", ru: "Морская удача" },
  "enchantment.lunge": { en: "Lunge", ru: "Выпад" },
  "enchantment.mending": { en: "Mending", ru: "Починка" },
  "enchantment.oxygen": { en: "Respiration", ru: "Дыхание" },
  "enchantment.protect.all": { en: "Protection", ru: "Защита" },
  "enchantment.protect.explosion": { en: "Blast Protection", ru: "Взрывоустойчивость" },
  "enchantment.protect.fall": { en: "Feather Falling", ru: "Легкость" },
  "enchantment.protect.fire": { en: "Fire Protection", ru: "Огнеупорность" },
  "enchantment.protect.projectile": { en: "Projectile Protection", ru: "Защита от снарядов" },
  "enchantment.soul_speed": { en: "Soul Speed", ru: "Скорость души" },
  "enchantment.swift_sneak": { en: "Swift Sneak", ru: "Быстрое подкрадывание" },
  "enchantment.thorns": { en: "Thorns", ru: "Шипы" },
  "enchantment.tridentChanneling": { en: "Channeling", ru: "Проводник" },
  "enchantment.tridentImpaling": { en: "Impaling", ru: "Пронзание" },
  "enchantment.tridentLoyalty": { en: "Loyalty", ru: "Верность" },
  "enchantment.tridentRiptide": { en: "Riptide", ru: "Тягун" },
  "enchantment.untouching": { en: "Silk Touch", ru: "Шелковое касание" },
  "enchantment.waterWalker": { en: "Depth Strider", ru: "Странник глубин" },
  "enchantment.waterWorker": { en: "Aqua Affinity", ru: "Родство с водой" },
};
